In [147]:
import numpy as np
import pandas as pd
import math

# s=pd.Series({'Google':np.random.normal(0, .2, 10),
#                            'Apple':np.random.normal(0, .2, 10),
#                            'Ebay':np.random.normal(0, .2, 10)})
s = pd.Series({'Google':[.2,.3,.4,-.2], 'Apple': [.3,.1,.3,.4],'Ebay':[.1,.7,-.1,-.2]})
x=s.values

# x = np.array([[0, 2 , 3], [1, 1, 6], [2, 0, 9]]).T

# np.cov(x)
# s = pd.Series({'a':[1,2], 'b':[2,3], 'c':[3,5]})
# u=np.array(s.values)
# u.astype(int)
# print(list(s.values))
returns=np.array(list(s.values))
cov_matrix=np.cov(np.array(list(s.values)))
print(cov)

[[ 0.02   0.01  -0.01 ]
 [ 0.01   0.005 -0.005]
 [-0.01  -0.005  0.005]]


In [148]:
# ticker= pd.Series({'Google':[1,2,3], 'Apple': [3,6,9], 'AMZN':[8,10,12]})
# cov_matrix=np.cov(np.array(list(ticker.values)))

In [149]:
diag=cov_matrix.diagonal()
diag_matrix=np.diag(np.diag(cov_matrix)) # gives n*n diagonal matrix
diag_matrix

array([[ 0.01583333,  0.        ,  0.        ],
       [ 0.        ,  0.1625    ,  0.        ],
       [ 0.        ,  0.        ,  0.06916667]])

In [150]:
from arch import arch_model
garch11 = arch_model(diag, p=1, q=1)
res = garch11.fit(update_freq=10)
print(res.summary())

Optimization terminated successfully.    (Exit mode 0)
            Current function value: -4.19895560621
            Iterations: 6
            Function evaluations: 41
            Gradient evaluations: 6
                     Constant Mean - GARCH Model Results                      
Dep. Variable:                      y   R-squared:                      -0.001
Mean Model:             Constant Mean   Adj. R-squared:                 -0.001
Vol Model:                      GARCH   Log-Likelihood:                4.19896
Distribution:                  Normal   AIC:                         -0.397911
Method:            Maximum Likelihood   BIC:                          -4.00346
                                        No. Observations:                    3
Date:                Thu, Feb 09 2017   Df Residuals:                       -1
Time:                        19:41:50   Df Model:                            4
                                  Mean Model                                  
     

In [151]:
alpha=res.params[2]
beta=res.params[3]
# std_err=np.random.normal(0, 1, 3) #epselon is the returns 

In [152]:
# esubt=np.linalg.inv(diag_matrix)
# ret=[.1,.2,.13] # just to see how it works
esubt=np.matmul(np.linalg.inv(diag_matrix),returns)
# esubt=np.matmul(np.linalg.inv(diag_matrix),returns)
esubt

array([[ 18.94736842,   6.31578947,  18.94736842,  25.26315789],
       [  0.61538462,   4.30769231,  -0.61538462,  -1.23076923],
       [  2.89156627,   4.3373494 ,   5.78313253,  -2.89156627]])

In [153]:
#not sure
qdash=np.cov(esubt)
q_start=np.ones((3,3))
qdash
# q_start

array([[ 63.15789474, -19.10931174, -19.02346227],
       [-19.10931174,   6.15384615,   4.22613531],
       [-19.02346227,   4.22613531,  14.45783133]])

In [154]:
q=((1-alpha-beta)*qdash) + (alpha*np.matmul(esubt,esubt.T)) + ((beta)*q_start)
q

array([[ 9.10497541, -1.62212019, -1.61092597],
       [-1.62212019,  1.67202718,  1.42066654],
       [-1.61092597,  1.42066654,  2.7548115 ]])

In [155]:
# r=np.matmul(np.linalg.inv(qdash),q)
qstar=np.diag(np.diag(cov_matrix))
qstar=np.sqrt(qstar)
qstar

array([[ 0.12583057,  0.        ,  0.        ],
       [ 0.        ,  0.40311289,  0.        ],
       [ 0.        ,  0.        ,  0.26299556]])

In [156]:
r=np.matmul(np.linalg.inv(qstar),q,np.linalg.inv(qstar))
r

array([[ 72.35900721, -12.89130408, -12.8023414 ],
       [ -4.02398495,   4.14778896,   3.52423995],
       [ -6.1252971 ,   5.40186504,  10.47474513]])

In [157]:
diag_matrix=np.diag(np.diag(cov_matrix))
print(diag_matrix)
predi_cov=np.matmul(diag_matrix,r)
predi_cov=np.matmul(predi_cov,diag_matrix)
print(predi_cov)

[[ 0.01583333  0.          0.        ]
 [ 0.          0.1625      0.        ]
 [ 0.          0.          0.06916667]]
[[ 0.01814    -0.03316825 -0.01402034]
 [-0.01035338  0.10952755  0.03961099]
 [-0.00670805  0.06071471  0.05011147]]


In [200]:
stock_returns = pd.Series({'Google':np.random.normal(0, .2, 10),
                           'Apple':np.random.normal(0, .2, 10),
                           'Ebay':np.random.normal(0, .2, 10)})


returns=np.array(list(stock_returns.values))
returns=returns[:,0:3]

#inititial condition setting esubt and q
esubt=[]
q_list=[]

cov_matrix=np.cov(returns)
diag=cov_matrix.diagonal()
diag_matrix=np.diag(np.diag(cov_matrix))
garch11 = arch_model(diag, p=1, q=1)
res = garch11.fit(update_freq=10)
alpha=res.params[2]
beta=res.params[3]

esubt.append(np.matmul(np.linalg.inv(diag_matrix),returns))
q_list.append(np.ones((3,3)))
pred_cov=[]

print(esubt)

def dccGARCH(returns):    
    cov_matrix=np.cov(returns)
    diag=cov_matrix.diagonal()
    diag_matrix=np.diag(np.diag(cov_matrix))
    
    garch11 = arch_model(diag, p=1, q=1)
    res = garch11.fit(update_freq=10)
    alpha=res.params[2]
    beta=res.params[3]    
    
    esubt.append(np.matmul(np.linalg.inv(diag_matrix),returns))
#     print(esubt)
#     print('\n')
#     print(np.matmul(esubt[-2],esubt[-2].T))
    qdash=np.cov(esubt[-2])
#    q_start=np.ones((3,3))
    
    q_list.append(((1-alpha-beta)*qdash) + 
             (alpha*np.matmul(esubt[-2],esubt[-2].T)) + ((beta)*q_list[-1]))
    
#     print("&&&&&")
    
    qstar=np.diag(np.diag(cov_matrix))
    qstar=np.sqrt(qstar)
    
    r=np.matmul(np.linalg.inv(qstar),q_list[-1],np.linalg.inv(qstar))
    
    pred_cov_temp=np.matmul(diag_matrix,r)
    pred_cov.append(np.matmul(pred_cov_temp,diag_matrix))
    
    print(pred_cov[-1])
    print(i)
    print('\n')
    

# dccGARCH(returns[:,0:4])
for i in range(4,10):
    dccGARCH(returns[:,0:i])

Optimization terminated successfully.    (Exit mode 0)
            Current function value: -8.51957264122
            Iterations: 9
            Function evaluations: 60
            Gradient evaluations: 7
[[ 0.06273415 -0.01739813  0.02091096]
 [-0.04173074  0.02392369  0.00585069]
 [ 0.03254832  0.00379672  0.03786037]]
4


Optimization terminated successfully.    (Exit mode 0)
            Current function value: -8.51957264122
            Iterations: 9
            Function evaluations: 60
            Gradient evaluations: 7
[[ 0.10195575 -0.0311977   0.03347009]
 [-0.07483004  0.04088156  0.00899802]
 [ 0.05209686  0.00583913  0.06372222]]
5


Optimization terminated successfully.    (Exit mode 0)
            Current function value: -8.51957264122
            Iterations: 9
            Function evaluations: 60
            Gradient evaluations: 7
[[ 0.1305268  -0.04125002  0.04261881]
 [-0.09894129  0.05323456  0.01129069]
 [ 0.06633703  0.00732693  0.08256135]]
6


Optimization termin

In [203]:
returns=np.array(list(stock_returns.values))
returns=returns[:,0:9]
np.cov(returns)

array([[ 0.0603572 ,  0.01057508,  0.01718304],
       [ 0.01057508,  0.03263117,  0.005009  ],
       [ 0.01718304,  0.005009  ,  0.02844886]])

In [228]:
def simulate_GARCH(T, a0, a1, b1, sigma1):
    
    # Initialize our values
    X = np.ndarray(T)
    sigma = np.ndarray(T)
    sigma[0] = sigma1
    
    for t in range(1, T):
        # Draw the next x_t
        X[t - 1] = sigma[t - 1] * np.random.normal(0, 1)
        # Draw the next sigma_t
        sigma[t] = math.sqrt(a0 + b1 * sigma[t - 1]**2 + a1 * X[t - 1]**2)
        
    X[T - 1] = sigma[T - 1] * np.random.normal(0, 1)    
    
    return X, sigma


In [246]:
returns=np.array(list(stock_returns.values))
returns[1]
print(returns[1])
garch11 = arch_model(returns[1], p=1, q=1)
res = garch11.fit(update_freq=10)
print(res.summary())

[  2.13216817e-01   4.77533758e-01   6.90381080e-02  -3.56626430e-01
  -3.00779093e-04   2.18676403e-01   1.25725657e-01   2.39171224e-01
  -1.73323174e-01   1.06894238e-01]


[ 0.25260784  0.08397638  0.20074615 -0.14971016  0.24701735  0.40326562
  0.05894982  0.27389894  0.43160178 -0.17473239]


[ 0.09647014  0.00516876 -0.165731   -0.26642407 -0.1077995  -0.05988453
  0.3254212  -0.02651457  0.03284334  0.11616235]


[ 0.25260784  0.08397638  0.20074615 -0.14971016  0.24701735  0.40326562
  0.05894982  0.27389894  0.43160178 -0.17473239]
Optimization terminated successfully.    (Exit mode 0)
            Current function value: -2.26601657678
            Iterations: 8
            Function evaluations: 54
            Gradient evaluations: 8
                     Constant Mean - GARCH Model Results                      
Dep. Variable:                      y   R-squared:                      -0.000
Mean Model:             Constant Mean   Adj. R-squared:                 -0.000
Vol Model

In [240]:
import math
omega=res.params[1]
alpha=res.params[2]
beta=res.params[3]
# sig_ma=np.sqrt(np.mean(returns[1]))
sig_ma=np.std(returns[1])  # Assumption that I am making
# print(sigma)
# sig_ma=0
# sigma = math.sqrt(omega / (1 - alpha - beta))
return_forecast,sigma_forecast=simulate_GARCH(5,omega,alpha,beta,sig_ma)
return_forecast


array([ 0.04201855,  0.06044578, -0.68989632, -0.16610597, -0.00166613])

In [243]:
np.append(returns[1],return_forecast)

array([ 0.25260784,  0.08397638,  0.20074615, -0.14971016,  0.24701735,
        0.40326562,  0.05894982,  0.27389894,  0.43160178, -0.17473239,
        0.04201855,  0.06044578, -0.68989632, -0.16610597, -0.00166613])