In [20]:
import numpy as np
import pandas as pd

s = pd.Series({'Google':[1,2,3], 'Apple': [2,4,5]})

x=s.values

x = np.array([[0, 2 , 3], [1, 1, 6], [2, 0, 9]]).T

np.cov(x)
s = pd.Series({'a':[1,2], 'b':[2,3], 'c':[3,5]})
u=np.array(s.values)
# u.astype(int)
print(list(s.values))
returns=np.array(list(s.values))
np.cov(np.array(list(s.values)))


[[1, 2], [2, 3], [3, 5]]


array([[ 0.5,  0.5,  1. ],
       [ 0.5,  0.5,  1. ],
       [ 1. ,  1. ,  2. ]])

In [5]:
ticker= pd.Series({'Google':[1,2,3], 'Apple': [3,6,9], 'AMZN':[8,10,12]})
cov_matrix=np.cov(np.array(list(ticker.values)))

In [6]:
diag=cov_matrix.diagonal()
diag_matrix=np.diag(np.diag(cov_matrix)) # gives n*n diagonal matrix

In [7]:
from arch import arch_model
garch11 = arch_model(diag, p=1, q=1)
res = garch11.fit(update_freq=10)
print(res.summary())

Iteration:     10,   Func. Count:     61,   Neg. LLF: 7.82206972268501
Optimization terminated successfully.    (Exit mode 0)
            Current function value: 7.81243826688
            Iterations: 15
            Function evaluations: 92
            Gradient evaluations: 15
                     Constant Mean - GARCH Model Results                      
Dep. Variable:                      y   R-squared:                      -0.000
Mean Model:             Constant Mean   Adj. R-squared:                 -0.000
Vol Model:                      GARCH   Log-Likelihood:               -7.81244
Distribution:                  Normal   AIC:                           23.6249
Method:            Maximum Likelihood   BIC:                           20.0193
                                        No. Observations:                    3
Date:                Thu, Feb 09 2017   Df Residuals:                       -1
Time:                        08:16:25   Df Model:                            4
            

In [8]:
alpha=res.params[2]
beta=res.params[3]
# std_err=np.random.normal(0, 1, 3) #epselon is the returns 

In [23]:
# esubt=np.linalg.inv(diag_matrix)
esubt=np.linalg.inv(diag_matrix)*returns
esubt

ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

In [13]:
#not sure
qdash=np.cov(esubt)
qdash

array([[ 0.00332015,  0.00122218,  0.00381816],
       [ 0.00122218,  0.0017996 , -0.00281101],
       [ 0.00381816, -0.00281101,  0.01756344]])

In [ ]:
q=((1-alpha-beta)*qdash) + (alpha*esubt*esubt.T) + (beta)

In [19]:
np.array(list(s.values))

array([[1, 2],
       [2, 3],
       [3, 5]])